### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Acksop** [windwalker-io/renderer#11]
I use renderer in my own framework, did you think to make an update of it for newer version of Blade and Twig?
Renderer is really awesome for me.
Thanks a lot, because : without your work, I not really do a stuff like my framework.

------
[SAND-framework](https://sand-framework.app)

**Comment by asika32764** [comment]
Which blade version did you use?

**Comment by Acksop** [comment]
The same reference I've found on one of your ancien website : illuminated/view 4.*

**Comment by Acksop** [comment]
and in the readme of 3.x of renderer

**Comment by Acksop** [comment]
Sorry... 

i have not seen that the 4.0.0 version of windwalker—renderer do it.

Is the commands of function needefd to render are the same ?

Do you like a little my work ? If not : tell me I will not use it.

Thanks in advance.

**Comment by asika32764** [comment]
I have tested Laravel 9.x for windwalker/renderer 3.x, it sill works fine. You can use this package for latest Laravel Blade version.

**Comment by Acksop** [comment]
Sorry... 

i have not seen that the 4.0.0 version of windwalker—renderer do it.

Is the commands of function needefd to render are the same ?

Do you like a little my work ? If not : tell me I will not use your renderer.

Thanks in advance.

**Comment by Acksop** [comment]
Re, I've tested with Laravel 9.x 
![FireShot Capture 030 - Accueil de l'application - dev sand local -- BLADE](https://user-images.githubusercontent.com/1587184/194636850-bafae8ed-a34c-43f6-be4d-f8db4c8aa7ad.png)
And Twig 2.x
![FireShot Capture 030 - Accueil de l'application - dev sand local - TWIG](https://user-images.githubusercontent.com/1587184/194636841-c27b1d58-0034-4c4d-976e-712fe0f67eac.png)

With PHP 8.1 there is some Deprecated Errors, see below.

**Comment by asika32764** [comment]
What is the version of windwalker/renderer & windwalker/structure that you installed?

**Comment by asika32764** [comment]
windwalker/renderer 3.x only supports Twig 1.x, there is no plan to suppoer twig 2.x later.

**Comment by Acksop** [comment]
![image](https://user-images.githubusercontent.com/1587184/195662837-ff718b71-68b1-4518-8af9-596d1d2ac2da.png)

**Comment by Acksop** [comment]
![image](https://user-images.githubusercontent.com/1587184/195663033-7d1e96af-4d20-4125-b896-89cc7073ebd5.png)

**Comment by Acksop** [comment]
and it works ...
